# Generated by Django 3.2.4 on 2021-06-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=8)),
                ('creationDate', models.DateField(auto_now_add=True)),
                ('expDate', models.DateField()),
            ],
        ),
    ]
