# Generated by Django 3.2.4 on 2021-06-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_key_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='key',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
